/**
 * Catálogo de emojis del selector del chat.
 *
 * Es una lista propia y no un paquete de npm a propósito: las librerías de
 * emojis traen los ~1800 del estándar con sus nombres en inglés y un JSON de
 * cientos de kB que habría que cargar en el cliente. Acá alcanza con los que
 * se usan hablando con un cliente, y los buscamos por palabras en castellano
 * rioplatense ("plata", "pancho", "mate", "birome") — que es lo que la persona
 * que atiende va a tipear.
 *
 * Cada entrada es `[emoji, palabras de búsqueda]`. Las palabras se comparan sin
 * acentos (ver `normalize` en emoji-picker.tsx), así que "limon" encuentra 🍋.
 */

export type EmojiEntry = readonly [emoji: string, keywords: string];

export type EmojiCategory = {
  /** Se usa como ancla del scroll y como key de React. */
  id: string;
  label: string;
  /** Emoji que representa la categoría en la barra de navegación. */
  icon: string;
  emojis: readonly EmojiEntry[];
};

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: "caras",
    label: "Caritas y gestos",
    icon: "😀",
    emojis: [
      ["😀", "sonrisa cara feliz contento"],
      ["😃", "sonrisa alegre feliz"],
      ["😄", "sonrisa feliz ojos alegre"],
      ["😁", "sonrisa dientes feliz"],
      ["😆", "risa carcajada"],
      ["😅", "risa sudor alivio nervios"],
      ["🤣", "risa carcajada revolcarse"],
      ["😂", "risa llanto lagrimas gracioso"],
      ["🙂", "sonrisa leve"],
      ["🙃", "cara al reves ironia"],
      ["😉", "guiño complice"],
      ["😊", "sonrisa sonrojo timido"],
      ["😇", "angel aureola inocente"],
      ["🥰", "enamorado corazones cariño"],
      ["😍", "ojos corazon amor enamorado"],
      ["🤩", "estrellas asombro flash"],
      ["😘", "beso volado cariño"],
      ["😗", "beso"],
      ["😚", "beso ojos cerrados"],
      ["😋", "rico delicioso lengua sabroso"],
      ["😛", "lengua afuera"],
      ["😜", "lengua guiño broma"],
      ["🤪", "loco chiflado"],
      ["🤑", "plata dinero guita"],
      ["🤗", "abrazo abrazar"],
      ["🤭", "risa taparse boca uy"],
      ["🤫", "silencio shh callate"],
      ["🤔", "pensar duda pensativo"],
      ["🤐", "boca cerrada cierre secreto"],
      ["🤨", "ceja levantada desconfianza"],
      ["😐", "neutral serio"],
      ["😑", "inexpresivo sin ganas"],
      ["😶", "sin boca mudo"],
      ["😏", "picardia sonrisita"],
      ["😒", "fastidio desganado"],
      ["🙄", "ojos para arriba obvio"],
      ["😬", "mueca incomodo tension"],
      ["🤥", "mentira nariz larga"],
      ["😌", "aliviado tranquilo en paz"],
      ["😔", "triste pensativo bajon"],
      ["😪", "sueño cansado"],
      ["😴", "dormir sueño zzz"],
      ["😷", "barbijo enfermo tapaboca"],
      ["🤒", "fiebre termometro enfermo"],
      ["🤕", "golpe herido venda"],
      ["🤢", "asco nauseas"],
      ["🤮", "vomito descompuesto"],
      ["🤧", "estornudo resfrio"],
      ["🥵", "calor sofocado"],
      ["🥶", "frio congelado"],
      ["🥴", "mareado borracho"],
      ["😵", "mareado aturdido"],
      ["🤯", "explota la cabeza asombro"],
      ["🤠", "vaquero"],
      ["🥳", "fiesta festejo cumpleaños"],
      ["😎", "lentes de sol copado genial"],
      ["🤓", "nerd anteojos"],
      ["🧐", "monoculo curioso"],
      ["😕", "confundido"],
      ["😟", "preocupado"],
      ["🙁", "triste"],
      ["😮", "sorpresa boca abierta"],
      ["😯", "sorprendido"],
      ["😲", "asombro impresionado"],
      ["😳", "sonrojado verguenza sorpresa"],
      ["🥺", "suplica ojitos porfa"],
      ["😨", "miedo susto"],
      ["😰", "miedo sudor angustia"],
      ["😥", "triste alivio"],
      ["😢", "llorar lagrima triste"],
      ["😭", "llorar a mares triste"],
      ["😱", "grito miedo panico"],
      ["😖", "frustrado"],
      ["😣", "aguantar esfuerzo"],
      ["😞", "decepcionado"],
      ["😓", "sudor bajon"],
      ["😩", "cansado agotado"],
      ["😫", "harto cansado"],
      ["🥱", "bostezo aburrido"],
      ["😤", "bufido enojo orgullo"],
      ["😡", "enojado furioso bronca"],
      ["😠", "enojado molesto"],
      ["🤬", "insulto puteada enojo"],
      ["😈", "diablo travieso"],
      ["👿", "diablo enojado"],
      ["💀", "calavera muerte muerto"],
      ["💩", "caca"],
      ["🤡", "payaso"],
      ["👻", "fantasma"],
      ["👽", "alien extraterrestre"],
      ["🤖", "robot bot"],
      ["😺", "gato sonrisa"],
      ["😻", "gato enamorado"],
      ["🙈", "mono no ver"],
      ["🙉", "mono no oir"],
      ["🙊", "mono no hablar"],
      ["👋", "hola saludo chau mano"],
      ["🤚", "mano levantada"],
      ["✋", "mano alto pare"],
      ["🖐️", "mano dedos abiertos"],
      ["👌", "ok perfecto barbaro"],
      ["🤌", "dedos italiano que haces"],
      ["🤏", "poquito chiquito"],
      ["✌️", "paz victoria"],
      ["🤞", "dedos cruzados suerte"],
      ["🤟", "te amo mano"],
      ["🤘", "rock cuernitos"],
      ["🤙", "llamame"],
      ["👈", "dedo izquierda"],
      ["👉", "dedo derecha"],
      ["👆", "dedo arriba"],
      ["👇", "dedo abajo aca"],
      ["☝️", "dedo arriba atencion"],
      ["👍", "like pulgar arriba dale bien"],
      ["👎", "dislike pulgar abajo mal"],
      ["✊", "puño fuerza"],
      ["👊", "puño golpe choque"],
      ["👏", "aplausos aplaudir bravo"],
      ["🙌", "manos arriba festejo gracias"],
      ["👐", "manos abiertas"],
      ["🤝", "apreton de manos trato acuerdo"],
      ["🙏", "gracias rezar porfavor"],
      ["💪", "fuerza musculo vamos"],
      ["🫶", "corazon con las manos cariño"],
      ["👶", "bebe"],
      ["🧒", "nene chico"],
      ["👦", "nene varon"],
      ["👧", "nena chica"],
      ["🧑", "persona"],
      ["👨", "hombre señor"],
      ["👩", "mujer señora"],
      ["🧓", "abuelo mayor"],
      ["👮", "policia"],
      ["👷", "obrero construccion"],
      ["🤵", "novio traje smoking"],
      ["👰", "novia casamiento"],
      ["🎅", "papa noel navidad"],
      ["💃", "bailar mujer fiesta"],
      ["🕺", "bailar hombre fiesta"],
      ["🧘", "yoga meditar relax"],
      ["💇", "corte de pelo peluqueria"],
      ["💆", "masaje spa relax"],
      ["💅", "uñas manicura esmalte"],
      ["🧖", "spa sauna vapor"],
      ["👪", "familia"],
      ["👥", "personas gente"],
    ],
  },
  {
    id: "naturaleza",
    label: "Animales y naturaleza",
    icon: "🌿",
    emojis: [
      ["🐶", "perro cachorro"],
      ["🐱", "gato michi"],
      ["🐭", "raton"],
      ["🐹", "hamster"],
      ["🐰", "conejo"],
      ["🦊", "zorro"],
      ["🐻", "oso"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🐯", "tigre"],
      ["🦁", "leon"],
      ["🐮", "vaca"],
      ["🐷", "chancho cerdo"],
      ["🐸", "rana sapo"],
      ["🐵", "mono"],
      ["🐔", "gallina"],
      ["🐧", "pinguino"],
      ["🐦", "pajaro"],
      ["🐤", "pollito"],
      ["🦆", "pato"],
      ["🦉", "buho lechuza"],
      ["🐺", "lobo"],
      ["🐴", "caballo"],
      ["🦄", "unicornio"],
      ["🐝", "abeja"],
      ["🦋", "mariposa"],
      ["🐌", "caracol"],
      ["🐞", "vaquita de san antonio"],
      ["🐜", "hormiga"],
      ["🕷️", "araña"],
      ["🐢", "tortuga"],
      ["🐍", "serpiente vibora"],
      ["🐙", "pulpo"],
      ["🦀", "cangrejo"],
      ["🐠", "pez tropical"],
      ["🐟", "pez pescado"],
      ["🐬", "delfin"],
      ["🐳", "ballena"],
      ["🦈", "tiburon"],
      ["🐊", "cocodrilo yacare"],
      ["🦓", "cebra"],
      ["🦍", "gorila"],
      ["🐘", "elefante"],
      ["🦒", "jirafa"],
      ["🐑", "oveja"],
      ["🐓", "gallo"],
      ["🕊️", "paloma paz"],
      ["🐕", "perro"],
      ["🐈", "gato"],
      ["🌸", "flor cerezo"],
      ["🌹", "rosa flor"],
      ["🥀", "flor marchita"],
      ["🌺", "flor hibisco"],
      ["🌻", "girasol flor"],
      ["🌼", "margarita flor"],
      ["🌷", "tulipan flor"],
      ["🌱", "brote planta"],
      ["🌲", "pino arbol"],
      ["🌳", "arbol"],
      ["🌴", "palmera"],
      ["🌵", "cactus"],
      ["🌾", "espiga trigo"],
      ["🌿", "hierba planta hoja"],
      ["🍀", "trebol suerte"],
      ["🍁", "hoja otoño"],
      ["🍂", "hojas otoño"],
      ["🍃", "hoja viento"],
      ["🍄", "hongo"],
      ["🌍", "mundo tierra planeta"],
      ["🌙", "luna noche"],
      ["⭐", "estrella"],
      ["🌟", "estrella brillo destacado"],
      ["✨", "brillos magia lindo"],
      ["⚡", "rayo energia luz"],
      ["🔥", "fuego fogon buenisimo"],
      ["🌈", "arcoiris"],
      ["☀️", "sol dia"],
      ["⛅", "nublado sol nube"],
      ["☁️", "nube"],
      ["🌧️", "lluvia"],
      ["❄️", "nieve copo frio"],
      ["⛄", "muñeco de nieve"],
      ["💧", "gota agua"],
      ["🌊", "ola mar playa"],
    ],
  },
  {
    id: "comida",
    label: "Comida y bebida",
    icon: "🍕",
    emojis: [
      ["🍎", "manzana fruta"],
      ["🍏", "manzana verde"],
      ["🍐", "pera"],
      ["🍊", "naranja mandarina"],
      ["🍋", "limón"],
      ["🍌", "banana"],
      ["🍉", "sandía"],
      ["🍇", "uvas"],
      ["🍓", "frutilla"],
      ["🫐", "arándanos"],
      ["🍒", "cerezas"],
      ["🍑", "durazno"],
      ["🥭", "mango"],
      ["🍍", "ananá piña"],
      ["🥥", "coco"],
      ["🥝", "kiwi"],
      ["🍅", "tomate"],
      ["🥑", "palta"],
      ["🍆", "berenjena"],
      ["🥕", "zanahoria"],
      ["🌽", "choclo maíz"],
      ["🥔", "papa"],
      ["🧄", "ajo"],
      ["🧅", "cebolla"],
      ["🥬", "lechuga verdura"],
      ["🥦", "brócoli"],
      ["🍞", "pan"],
      ["🥐", "medialuna croissant"],
      ["🥖", "pan flauta baguette"],
      ["🧀", "queso"],
      ["🥚", "huevo"],
      ["🍳", "huevo frito desayuno"],
      ["🥓", "panceta"],
      ["🥩", "carne bife asado"],
      ["🍗", "pata de pollo"],
      ["🍔", "hamburguesa"],
      ["🍟", "papas fritas"],
      ["🍕", "pizza"],
      ["🌭", "pancho"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🥗", "ensalada"],
      ["🍝", "fideos pasta"],
      ["🍜", "ramen sopa"],
      ["🍲", "guiso puchero olla"],
      ["🍣", "sushi"],
      ["🍤", "langostino"],
      ["🍚", "arroz"],
      ["🥟", "empanada"],
      ["🍿", "pochoclo"],
      ["🧂", "sal"],
      ["🍦", "helado"],
      ["🍨", "helado copa"],
      ["🍩", "dona"],
      ["🍪", "galletita"],
      ["🎂", "torta cumpleaños"],
      ["🍰", "porción de torta"],
      ["🧁", "cupcake magdalena"],
      ["🥧", "tarta"],
      ["🍫", "chocolate"],
      ["🍬", "caramelo"],
      ["🍭", "chupetín"],
      ["🍯", "miel"],
      ["🥛", "leche vaso"],
      ["☕", "café"],
      ["🧉", "mate"],
      ["🍵", "té"],
      ["🧃", "jugo"],
      ["🥤", "gaseosa vaso"],
      ["🍺", "cerveza birra"],
      ["🍻", "brindis cerveza"],
      ["🍷", "vino copa"],
      ["🥂", "brindis champagne festejo"],
      ["🍸", "trago cóctel"],
      ["🍾", "champagne festejo"],
      ["🥃", "whisky"],
    ],
  },
  {
    id: "actividades",
    label: "Actividades",
    icon: "⚽",
    emojis: [
      ["⚽", "fútbol pelota"],
      ["🏀", "básquet"],
      ["🏈", "fútbol americano"],
      ["⚾", "béisbol"],
      ["🎾", "tenis"],
      ["🏐", "vóley"],
      ["🏉", "rugby"],
      ["🎱", "pool billar"],
      ["🏓", "ping pong"],
      ["🥊", "boxeo"],
      ["🥋", "karate judo"],
      ["⛳", "golf"],
      ["🎣", "pesca"],
      ["🏋️", "pesas gimnasio"],
      ["🤸", "gimnasia"],
      ["🚴", "bici ciclismo"],
      ["🏆", "trofeo ganar campeón"],
      ["🥇", "medalla oro primero"],
      ["🥈", "medalla plata"],
      ["🥉", "medalla bronce"],
      ["🏅", "medalla"],
      ["🎯", "dardos objetivo meta"],
      ["🎮", "videojuego joystick"],
      ["🎲", "dado"],
      ["🎳", "bowling"],
      ["🎭", "teatro máscaras"],
      ["🎨", "arte pintura"],
      ["🎤", "micrófono cantar"],
      ["🎧", "auriculares música"],
      ["🎵", "nota música"],
      ["🎶", "música notas"],
      ["🎸", "guitarra"],
      ["🎹", "piano teclado"],
      ["🥁", "batería tambor"],
      ["🎺", "trompeta"],
      ["🎷", "saxo"],
      ["🎬", "cine claqueta"],
      ["🎪", "circo"],
      ["🎉", "festejo fiesta felicitaciones"],
      ["🎊", "confeti fiesta"],
      ["🎈", "globo fiesta cumpleaños"],
      ["🎁", "regalo"],
      ["🎀", "moño lazo"],
      ["🎃", "halloween calabaza"],
      ["🎄", "navidad arbolito"],
      ["🧨", "cohete petardo"],
    ],
  },
  {
    id: "viajes",
    label: "Viajes y lugares",
    icon: "🚗",
    emojis: [
      ["🚗", "auto coche"],
      ["🚕", "taxi"],
      ["🚙", "camioneta"],
      ["🚌", "colectivo bondi bus"],
      ["🏎️", "auto de carrera"],
      ["🚓", "patrullero policía"],
      ["🚑", "ambulancia"],
      ["🚒", "bomberos"],
      ["🚐", "combi van"],
      ["🚚", "camión"],
      ["🚜", "tractor"],
      ["🛵", "moto scooter"],
      ["🏍️", "moto"],
      ["🚲", "bici"],
      ["🛴", "monopatín"],
      ["🚨", "sirena emergencia urgente"],
      ["✈️", "avión"],
      ["🚀", "cohete despegue"],
      ["🚁", "helicóptero"],
      ["⛵", "velero barco"],
      ["🚢", "barco crucero"],
      ["⚓", "ancla"],
      ["🚂", "tren locomotora"],
      ["🚆", "tren"],
      ["🚇", "subte metro"],
      ["🗺️", "mapa"],
      ["🧭", "brújula"],
      ["🏔️", "montaña"],
      ["🌋", "volcán"],
      ["🏕️", "camping carpa"],
      ["🏖️", "playa sombrilla vacaciones"],
      ["🏝️", "isla"],
      ["🏠", "casa"],
      ["🏡", "casa con jardín"],
      ["🏢", "oficina edificio"],
      ["🏥", "hospital"],
      ["🏦", "banco"],
      ["🏨", "hotel"],
      ["🏪", "kiosco tienda"],
      ["🏫", "escuela"],
      ["🏬", "shopping tienda"],
      ["🏭", "fábrica"],
      ["🏰", "castillo"],
      ["⛪", "iglesia"],
      ["🌆", "ciudad atardecer"],
      ["🌃", "ciudad de noche"],
      ["🌇", "atardecer"],
      ["🎡", "vuelta al mundo"],
      ["🎢", "montaña rusa"],
    ],
  },
  {
    id: "objetos",
    label: "Objetos",
    icon: "💡",
    emojis: [
      ["⌚", "reloj pulsera"],
      ["📱", "celular teléfono"],
      ["💻", "notebook computadora"],
      ["🖥️", "monitor computadora"],
      ["⌨️", "teclado"],
      ["🖨️", "impresora"],
      ["🖱️", "mouse"],
      ["📷", "cámara foto"],
      ["📸", "cámara flash foto"],
      ["📹", "filmadora video"],
      ["🎥", "cámara cine"],
      ["📞", "teléfono llamada"],
      ["☎️", "teléfono"],
      ["📺", "tele televisión"],
      ["📻", "radio"],
      ["🔋", "batería"],
      ["🔌", "enchufe"],
      ["💡", "idea lámpara luz"],
      ["🔦", "linterna"],
      ["🕯️", "vela"],
      ["💸", "plata volando gasto"],
      ["💵", "billete plata dólar"],
      ["💰", "plata bolsa dinero"],
      ["💳", "tarjeta crédito débito pago"],
      ["🧾", "factura recibo ticket comprobante"],
      ["💎", "diamante joya"],
      ["⚖️", "balanza justicia"],
      ["🔧", "llave herramienta arreglo"],
      ["🔨", "martillo"],
      ["🛠️", "herramientas arreglo"],
      ["🔩", "tornillo tuerca"],
      ["⚙️", "engranaje configuración"],
      ["🧰", "caja de herramientas"],
      ["💊", "pastilla remedio"],
      ["💉", "inyección vacuna"],
      ["🩺", "estetoscopio médico"],
      ["🩹", "curita"],
      ["🚪", "puerta"],
      ["🛏️", "cama"],
      ["🛋️", "sillón sofá"],
      ["🚿", "ducha"],
      ["🛁", "bañera"],
      ["🧴", "crema loción"],
      ["🧹", "escoba limpieza"],
      ["🧼", "jabón"],
      ["🪥", "cepillo de dientes"],
      ["🔑", "llave"],
      ["🔒", "candado cerrado privado"],
      ["🔓", "candado abierto"],
      ["🔔", "campana aviso notificación"],
      ["🔕", "silencio campana"],
      ["📢", "megáfono anuncio"],
      ["📣", "megáfono aviso"],
      ["✉️", "sobre carta mail"],
      ["📧", "mail correo"],
      ["📩", "mensaje sobre"],
      ["📦", "paquete caja envío"],
      ["📝", "nota escribir anotar"],
      ["✏️", "lápiz"],
      ["🖊️", "birome lapicera"],
      ["📄", "hoja documento"],
      ["📊", "gráfico barras estadística"],
      ["📈", "gráfico sube crecimiento ventas"],
      ["📉", "gráfico baja caída"],
      ["📋", "planilla portapapeles"],
      ["📌", "chinche importante"],
      ["📍", "ubicación pin dirección"],
      ["📎", "clip adjunto"],
      ["📁", "carpeta"],
      ["🗓️", "calendario agenda turno"],
      ["📅", "calendario fecha turno día"],
      ["🗒️", "anotador"],
      ["📒", "cuaderno"],
      ["📕", "libro"],
      ["📚", "libros"],
      ["🔍", "lupa buscar"],
      ["📡", "antena satélite"],
      ["💈", "peluquería barbería"],
      ["💄", "labial maquillaje"],
      ["💋", "beso labios"],
      ["👄", "labios boca"],
      ["👁️", "ojo"],
      ["👀", "ojos mirar atento"],
      ["🦷", "diente dentista"],
      ["🧠", "cerebro"],
      ["✂️", "tijera cortar corte"],
      ["🪒", "afeitadora navaja"],
      ["👗", "vestido ropa"],
      ["👠", "taco zapato"],
      ["👜", "cartera"],
      ["👓", "anteojos"],
      ["🕶️", "lentes de sol"],
      ["👑", "corona reina rey"],
      ["💍", "anillo casamiento"],
      ["🧢", "gorra"],
      ["👕", "remera ropa"],
      ["👖", "jean pantalón"],
      ["👟", "zapatillas"],
    ],
  },
  {
    id: "simbolos",
    label: "Símbolos",
    icon: "❤️",
    emojis: [
      ["❤️", "corazón rojo amor"],
      ["🧡", "corazón naranja"],
      ["💛", "corazón amarillo"],
      ["💚", "corazón verde"],
      ["💙", "corazón azul"],
      ["💜", "corazón violeta"],
      ["🖤", "corazón negro"],
      ["🤍", "corazón blanco"],
      ["💔", "corazón roto"],
      ["💕", "corazones amor"],
      ["💞", "corazones girando"],
      ["💓", "corazón latido"],
      ["💖", "corazón brillante"],
      ["💘", "corazón flecha cupido"],
      ["💝", "corazón regalo"],
      ["💯", "cien perfecto total"],
      ["✅", "tilde listo ok hecho"],
      ["☑️", "tilde casilla"],
      ["✔️", "tilde ok"],
      ["❌", "equis error no cancelado"],
      ["⭕", "círculo"],
      ["🚫", "prohibido no"],
      ["⚠️", "atención advertencia cuidado"],
      ["❗", "exclamación importante"],
      ["❓", "pregunta duda"],
      ["💤", "dormir zzz"],
      ["💢", "enojo bronca"],
      ["💥", "explosión choque"],
      ["💫", "mareo estrella"],
      ["💦", "gotas"],
      ["💨", "viento apuro rápido"],
      ["⏰", "despertador alarma recordatorio"],
      ["⏳", "reloj de arena esperar"],
      ["🕐", "hora reloj horario"],
      ["➕", "más suma"],
      ["➖", "menos resta"],
      ["✖️", "por multiplicar"],
      ["➗", "dividir"],
      ["♾️", "infinito"],
      ["🔝", "top arriba"],
      ["🆗", "ok listo"],
      ["🆕", "nuevo"],
      ["🆓", "gratis"],
      ["🔴", "círculo rojo"],
      ["🟢", "círculo verde"],
      ["🟡", "círculo amarillo"],
      ["🔵", "círculo azul"],
      ["⚫", "círculo negro"],
      ["⚪", "círculo blanco"],
      ["🔺", "triángulo rojo"],
      ["♻️", "reciclar"],
      ["🔄", "actualizar refrescar cambio"],
      ["🔁", "repetir"],
      ["▶️", "play reproducir"],
      ["⏸️", "pausa"],
      ["⏹️", "stop parar"],
      ["🔊", "volumen sonido audio"],
      ["🔇", "mudo silencio"],
      ["🏁", "bandera meta final"],
      ["🚩", "bandera marcar"],
      ["🏳️‍🌈", "bandera orgullo arcoiris lgbt"],
      ["🇦🇷", "argentina bandera"],
      ["🇺🇾", "uruguay bandera"],
      ["🇧🇷", "brasil bandera"],
      ["🇨🇱", "chile bandera"],
      ["🇵🇾", "paraguay bandera"],
      ["🇧🇴", "bolivia bandera"],
      ["🇵🇪", "perú bandera"],
      ["🇨🇴", "colombia bandera"],
      ["🇲🇽", "méxico bandera"],
      ["🇪🇸", "españa bandera"],
      ["🇺🇸", "estados unidos bandera"],
      ["🇮🇹", "italia bandera"],
      ["🇫🇷", "francia bandera"],
      ["🇩🇪", "alemania bandera"],
      ["🇬🇧", "reino unido inglaterra bandera"],
      ["🇵🇹", "portugal bandera"],
      ["🇯🇵", "japón bandera"],
    ],
  },
];

/** Los que ofrece el selector la primera vez, antes de tener historial. */
export const DEFAULT_RECENTS: readonly string[] = [
  "👍",
  "🙏",
  "😊",
  "❤️",
  "😂",
  "✅",
  "💪",
  "🎉",
];
